import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";

import { Montserrat, DotGothic16 } from "next/font/google";

export const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});
export const dotgothic = DotGothic16({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-goth",
});
export const metadata: Metadata = {
  title: "cuongduong.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${dotgothic.variable}`}>
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
